const thaiData = {
    consonants: [
        { char: "ก", thaiName: "ก ไก่", name: "ko kai", meaning: "chicken", class: "mid" },
        { char: "ข", thaiName: "ข ไข่", name: "kho khai", meaning: "egg", class: "high" },
        { char: "ฃ", thaiName: "ฃ ขวด", name: "kho khuat", meaning: "bottle (obsolete)", class: "high" },
        { char: "ค", thaiName: "ค ควาย", name: "kho khwai", meaning: "buffalo", class: "low" },
        { char: "ฅ", thaiName: "ฅ คน", name: "kho khon", meaning: "person (obsolete)", class: "low" },
        { char: "ฆ", thaiName: "ฆ ระฆัง", name: "kho rakhang", meaning: "bell", class: "low" },
        { char: "ง", thaiName: "ง งู", name: "ngo ngu", meaning: "snake", class: "low" },
        { char: "จ", thaiName: "จ จาน", name: "cho chan", meaning: "plate", class: "mid" },
        { char: "ฉ", thaiName: "ฉ ฉิ่ง", name: "cho ching", meaning: "cymbals", class: "high" },
        { char: "ช", thaiName: "ช ช้าง", name: "cho chang", meaning: "elephant", class: "low" },
        { char: "ซ", thaiName: "ซ โซ่", name: "so so", meaning: "chain", class: "low" },
        { char: "ฌ", thaiName: "ฌ เฌอ", name: "cho choe", meaning: "tree", class: "low" },
        { char: "ญ", thaiName: "ญ หญิง", name: "yo ying", meaning: "woman", class: "low" },
        { char: "ฎ", thaiName: "ฎ ชฎา", name: "do chada", meaning: "headdress", class: "mid" },
        { char: "ฏ", thaiName: "ฏ ปฏัก", name: "to patak", meaning: "spear/goad", class: "mid" },
        { char: "ฐ", thaiName: "ฐ ฐาน", name: "tho than", meaning: "base", class: "high" },
        { char: "ฑ", thaiName: "ฑ มณโฑ", name: "tho montho", meaning: "Montho (mythical character)", class: "low" },
        { char: "ฒ", thaiName: "ฒ ผู้เฒ่า", name: "tho phu-thao", meaning: "elder", class: "low" },
        { char: "ณ", thaiName: "ณ เณร", name: "no nen", meaning: "novice monk", class: "low" },
        { char: "ด", thaiName: "ด เด็ก", name: "do dek", meaning: "child", class: "mid" },
        { char: "ต", thaiName: "ต เต่า", name: "to tao", meaning: "turtle", class: "mid" },
        { char: "ถ", thaiName: "ถ ถุง", name: "tho thung", meaning: "sack/bag", class: "high" },
        { char: "ท", thaiName: "ท ทหาร", name: "tho thahan", meaning: "soldier", class: "low" },
        { char: "ธ", thaiName: "ธ ธง", name: "tho thong", meaning: "flag", class: "low" },
        { char: "น", thaiName: "น หนู", name: "no nu", meaning: "mouse", class: "low" },
        { char: "บ", thaiName: "บ ใบไม้", name: "bo baimai", meaning: "leaf", class: "mid" },
        { char: "ป", thaiName: "ป ปลา", name: "po pla", meaning: "fish", class: "mid" },
        { char: "ผ", thaiName: "ผ ผึ้ง", name: "pho phung", meaning: "bee", class: "high" },
        { char: "ฝ", thaiName: "ฝ ฝา", name: "fo fa", meaning: "lid", class: "high" },
        { char: "พ", thaiName: "พ พาน", name: "pho phan", meaning: "tray", class: "low" },
        { char: "ฟ", thaiName: "ฟ ฟัน", name: "fo fan", meaning: "teeth", class: "low" },
        { char: "ภ", thaiName: "ภ สำเภา", name: "pho sam-phao", meaning: "sailboat", class: "low" },
        { char: "ม", thaiName: "ม ม้า", name: "mo ma", meaning: "horse", class: "low" },
        { char: "ย", thaiName: "ย ยักษ์", name: "yo yak", meaning: "giant", class: "low" },
        { char: "ร", thaiName: "ร เรือ", name: "ro ruea", meaning: "boat", class: "low" },
        { char: "ล", thaiName: "ล ลิง", name: "lo ling", meaning: "monkey", class: "low" },
        { char: "ว", thaiName: "ว แหวน", name: "wo waen", meaning: "ring", class: "low" },
        { char: "ศ", thaiName: "ศ ศาลา", name: "so sala", meaning: "pavilion", class: "high" },
        { char: "ษ", thaiName: "ษ ฤๅษี", name: "so rusi", meaning: "hermit", class: "high" },
        { char: "ส", thaiName: "ส เสือ", name: "so sua", meaning: "tiger", class: "high" },
        { char: "ห", thaiName: "ห หีบ", name: "ho hip", meaning: "chest/box", class: "high" },
        { char: "ฬ", thaiName: "ฬ จุฬา", name: "lo chu-la", meaning: "kite", class: "low" },
        { char: "อ", thaiName: "อ อ่าง", name: "o ang", meaning: "basin", class: "mid" },
        { char: "ฮ", thaiName: "ฮ นกฮูก", name: "ho nok-huk", meaning: "owl", class: "low" }
    ],
    vowels: [
        { char: "ะ", thaiName: "สระอะ", name: "sara a", type: "short" },
        { char: "า", thaiName: "สระอา", name: "sara aa", type: "long" },
        { char: "ิ", thaiName: "สระอิ", name: "sara i", type: "short" },
        { char: "ี", thaiName: "สระอี", name: "sara ii", type: "long" },
        { char: "ึ", thaiName: "สระอึ", name: "sara ue", type: "short" },
        { char: "ื", thaiName: "สระอือ", name: "sara uee", type: "long" },
        { char: "ุ", thaiName: "สระอุ", name: "sara u", type: "short" },
        { char: "ู", thaiName: "สระอู", name: "sara uu", type: "long" },
        { char: "เ-ะ", thaiName: "สระเอะ", name: "sara e", type: "short" },
        { char: "เ-", thaiName: "สระเอ", name: "sara ee", type: "long" },
        { char: "แ-ะ", thaiName: "สระแอะ", name: "sara ae", type: "short" },
        { char: "แ-", thaiName: "สระแอ", name: "sara aee", type: "long" },
        { char: "โ-ะ", thaiName: "สระโอะ", name: "sara o", type: "short" },
        { char: "โ-", thaiName: "สระโอ", name: "sara oo", type: "long" },
        { char: "เ-าะ", thaiName: "สระเอาะ", name: "sara aw", type: "short" },
        { char: "อ", thaiName: "สระออ", name: "sara aww", type: "long" },
        { char: "เ-อะ", thaiName: "สระเออะ", name: "sara oe", type: "short" },
        { char: "เ-อ", thaiName: "สระเออ", name: "sara oee", type: "long" },
        { char: "เ-ียะ", thaiName: "สระเอียะ", name: "sara ia", type: "short" },
        { char: "เ-ีย", thaiName: "สระเอีย", name: "sara iaa", type: "long" },
        { char: "เ-ือะ", thaiName: "สระเอือะ", name: "sara uea", type: "short" },
        { char: "เ-ือ", thaiName: "สระเอือ", name: "sara ueaa", type: "long" },
        { char: "ัวะ", thaiName: "สระอัวะ", name: "sara ua", type: "short" },
        { char: "ัว", thaiName: "สระอัว", name: "sara uaa", type: "long" },
        { char: "อำ", thaiName: "สระอำ", name: "sara am", type: "special" },
        { char: "ใ-", thaiName: "สระไอไม้ม้วน", name: "sara ai mai-muan", type: "special" },
        { char: "ไ-", thaiName: "สระไอไม้มลาย", name: "sara ai mai-malay", type: "special" },
        { char: "เ-า", thaiName: "สระเอา", name: "sara ao", type: "special" }
    ]
};
