const thaiData = {
    consonants: [
        { char: "ก", name: "ko kai", meaning: "chicken", class: "mid" },
        { char: "ข", name: "kho khai", meaning: "egg", class: "high" },
        { char: "ฃ", name: "kho khuat", meaning: "bottle (obsolete)", class: "high" },
        { char: "ค", name: "kho khwai", meaning: "buffalo", class: "low" },
        { char: "ฅ", name: "kho khon", meaning: "person (obsolete)", class: "low" },
        { char: "ฆ", name: "kho rakhang", meaning: "bell", class: "low" },
        { char: "ง", name: "ngo ngu", meaning: "snake", class: "low" },
        { char: "จ", name: "cho chan", meaning: "plate", class: "mid" },
        { char: "ฉ", name: "cho ching", meaning: "cymbals", class: "high" },
        { char: "ช", name: "cho chang", meaning: "elephant", class: "low" },
        { char: "ซ", name: "so so", meaning: "chain", class: "low" },
        { char: "ฌ", name: "cho choe", meaning: "tree", class: "low" },
        { char: "ญ", name: "yo ying", meaning: "woman", class: "low" },
        { char: "ฎ", name: "do chada", meaning: "headdress", class: "mid" },
        { char: "ฏ", name: "to patak", meaning: "spear/goad", class: "mid" },
        { char: "ฐ", name: "tho than", meaning: "base", class: "high" },
        { char: "ฑ", name: "tho montho", meaning: "Montho (mythical character)", class: "low" },
        { char: "ฒ", name: "tho phu-thao", meaning: "elder", class: "low" },
        { char: "ณ", name: "no nen", meaning: "novice monk", class: "low" },
        { char: "ด", name: "do dek", meaning: "child", class: "mid" },
        { char: "ต", name: "to tao", meaning: "turtle", class: "mid" },
        { char: "ถ", name: "tho thung", meaning: "sack/bag", class: "high" },
        { char: "ท", name: "tho thahan", meaning: "soldier", class: "low" },
        { char: "ธ", name: "tho thong", meaning: "flag", class: "low" },
        { char: "น", name: "no nu", meaning: "mouse", class: "low" },
        { char: "บ", name: "bo baimai", meaning: "leaf", class: "mid" },
        { char: "ป", name: "po pla", meaning: "fish", class: "mid" },
        { char: "ผ", name: "pho phung", meaning: "bee", class: "high" },
        { char: "ฝ", name: "fo fa", meaning: "lid", class: "high" },
        { char: "พ", name: "pho phan", meaning: "tray", class: "low" },
        { char: "ฟ", name: "fo fan", meaning: "teeth", class: "low" },
        { char: "ภ", name: "pho sam-phao", meaning: "sailboat", class: "low" },
        { char: "ม", name: "mo ma", meaning: "horse", class: "low" },
        { char: "ย", name: "yo yak", meaning: "giant", class: "low" },
        { char: "ร", name: "ro ruea", meaning: "boat", class: "low" },
        { char: "ล", name: "lo ling", meaning: "monkey", class: "low" },
        { char: "ว", name: "wo waen", meaning: "ring", class: "low" },
        { char: "ศ", name: "so sala", meaning: "pavilion", class: "high" },
        { char: "ษ", name: "so rusi", meaning: "hermit", class: "high" },
        { char: "ส", name: "so sua", meaning: "tiger", class: "high" },
        { char: "ห", name: "ho hip", meaning: "chest/box", class: "high" },
        { char: "ฬ", name: "lo chu-la", meaning: "kite", class: "low" },
        { char: "อ", name: "o ang", meaning: "basin", class: "mid" },
        { char: "ฮ", name: "ho nok-huk", meaning: "owl", class: "low" }
    ],
    vowels: [
        { char: "ะ", name: "sara a", type: "short" },
        { char: "า", name: "sara aa", type: "long" },
        { char: "ิ", name: "sara i", type: "short" },
        { char: "ี", name: "sara ii", type: "long" },
        { char: "ึ", name: "sara ue", type: "short" },
        { char: "ื", name: "sara uee", type: "long" },
        { char: "ุ", name: "sara u", type: "short" },
        { char: "ู", name: "sara uu", type: "long" },
        { char: "เ-ะ", name: "sara e", type: "short" },
        { char: "เ-", name: "sara ee", type: "long" },
        { char: "แ-ะ", name: "sara ae", type: "short" },
        { char: "แ-", name: "sara aee", type: "long" },
        { char: "โ-ะ", name: "sara o", type: "short" },
        { char: "โ-", name: "sara oo", type: "long" },
        { char: "เ-าะ", name: "sara aw", type: "short" },
        { char: "อ", name: "sara aww", type: "long" },
        { char: "เ-อะ", name: "sara oe", type: "short" },
        { char: "เ-อ", name: "sara oee", type: "long" },
        { char: "เ-ียะ", name: "sara ia", type: "short" },
        { char: "เ-ีย", name: "sara iaa", type: "long" },
        { char: "เ-ือะ", name: "sara uea", type: "short" },
        { char: "เ-ือ", name: "sara ueaa", type: "long" },
        { char: "ัวะ", name: "sara ua", type: "short" },
        { char: "ัว", name: "sara uaa", type: "long" },
        { char: "อำ", name: "sara am", type: "special" },
        { char: "ใ-", name: "sara ai mai-muan", type: "special" },
        { char: "ไ-", name: "sara ai mai-malay", type: "special" },
        { char: "เ-า", name: "sara ao", type: "special" }
    ]
};
