const vocabularyData = [
    { "thai": "สวัสดี", "traditional": "你好", "pronunciation": "sa-wat-dee", "category": "Greetings" },
    { "thai": "ขอบคุณ", "traditional": "謝謝", "pronunciation": "khop-khun", "category": "Greetings" },
    { "thai": "ใช่", "traditional": "是", "pronunciation": "chai", "category": "Basics" },
    { "thai": "ไม่ใช่", "traditional": "不是", "pronunciation": "mai-chai", "category": "Basics" },
    { "thai": "กิน", "traditional": "吃", "pronunciation": "gin", "category": "Actions" },
    { "thai": "ไป", "traditional": "去", "pronunciation": "bpai", "category": "Actions" },
    { "thai": "รัก", "traditional": "愛", "pronunciation": "rak", "category": "Feelings" },
    { "thai": "หิว", "traditional": "餓", "pronunciation": "hiw", "category": "Feelings" },
    { "thai": "น้ำ", "traditional": "水", "pronunciation": "naam", "category": "Food & Drink" },
    { "thai": "ข้าว", "traditional": "飯", "pronunciation": "kaao", "category": "Food & Drink" },
    { "thai": "แมว", "traditional": "貓", "pronunciation": "maew", "category": "Animals" },
    { "thai": "หมา", "traditional": "狗", "pronunciation": "maa", "category": "Animals" },
    { "thai": "สบายดีไหม", "traditional": "你好嗎", "pronunciation": "sa-baai-dee-mai", "category": "Greetings" },
    { "thai": "ขอโทษ", "traditional": "對不起", "pronunciation": "khor-toht", "category": "Greetings" },
    { "thai": "ไม่เป็นไร", "traditional": "沒關係", "pronunciation": "mai-pen-rai", "category": "Greetings" },
    { "thai": "ยินดีที่ได้รู้จัก", "traditional": "很高興認識你", "pronunciation": "yin-dee-tee-dai-roo-jak", "category": "Greetings" },
    { "thai": "ลาก่อน", "traditional": "再見", "pronunciation": "laa-gorn", "category": "Greetings" },
    { "thai": "ที่นี่", "traditional": "這裡", "pronunciation": "tee-nee", "category": "Basics" },
    { "thai": "ที่นั่น", "traditional": "那裡", "pronunciation": "tee-nan", "category": "Basics" },
    { "thai": "ที่ไหน", "traditional": "哪裡", "pronunciation": "tee-nai", "category": "Basics" },
    { "thai": "อะไร", "traditional": "什麼", "pronunciation": "a-rai", "category": "Basics" },
    { "thai": "เมื่อไหร่", "traditional": "什麼時候", "pronunciation": "mua-rai", "category": "Basics" },
    { "thai": "ทำไม", "traditional": "為什麼", "pronunciation": "tam-mai", "category": "Basics" },
    { "thai": "อย่างไร", "traditional": "如何", "pronunciation": "yaang-rai", "category": "Basics" },
    { "thai": "ใคร", "traditional": "誰", "pronunciation": "krai", "category": "Basics" },
    { "thai": "เท่าไหร่", "traditional": "多少", "pronunciation": "tao-rai", "category": "Basics" },
    { "thai": "มาก", "traditional": "很多", "pronunciation": "maak", "category": "Basics" },
    { "thai": "น้อย", "traditional": "很少", "pronunciation": "noy", "category": "Basics" },
    { "thai": "ดี", "traditional": "好", "pronunciation": "dee", "category": "Basics" },
    { "thai": "เลว", "traditional": "壞", "pronunciation": "leo", "category": "Basics" },
    { "thai": "ร้อน", "traditional": "熱", "pronunciation": "rorn", "category": "Basics" },
    { "thai": "หนาว", "traditional": "冷", "pronunciation": "naao", "category": "Basics" },
    { "thai": "ดื่ม", "traditional": "喝", "pronunciation": "deum", "category": "Actions" },
    { "thai": "นอน", "traditional": "睡覺", "pronunciation": "norn", "category": "Actions" },
    { "thai": "เดิน", "traditional": "走路", "pronunciation": "dern", "category": "Actions" },
    { "thai": "วิ่ง", "traditional": "跑步", "pronunciation": "wing", "category": "Actions" },
    { "thai": "พูด", "traditional": "說話", "pronunciation": "poot", "category": "Actions" },
    { "thai": "ฟัง", "traditional": "聽", "pronunciation": "fang", "category": "Actions" },
    { "thai": "อ่าน", "traditional": "讀", "pronunciation": "aan", "category": "Actions" },
    { "thai": "เขียน", "traditional": "寫", "pronunciation": "kian", "category": "Actions" },
    { "thai": "ดู", "traditional": "看", "pronunciation": "doo", "category": "Actions" },
    { "thai": "เรียน", "traditional": "學習", "pronunciation": "rian", "category": "Actions" },
    { "thai": "ทำงาน", "traditional": "工作", "pronunciation": "tam-ngaan", "category": "Actions" },
    { "thai": "ซื้อ", "traditional": "買", "pronunciation": "seu", "category": "Actions" },
    { "thai": "ขาย", "traditional": "賣", "pronunciation": "kaai", "category": "Actions" },
    { "thai": "เข้าใจ", "traditional": "理解", "pronunciation": "kao-jai", "category": "Actions" },
    { "thai": "จำ", "traditional": "記得", "pronunciation": "jam", "category": "Actions" },
    { "thai": "ลืม", "traditional": "忘記", "pronunciation": "leum", "category": "Actions" },
    { "thai": "มีความสุข", "traditional": "快樂", "pronunciation": "mee-kwaam-sook", "category": "Feelings" },
    { "thai": "เศร้า", "traditional": "悲傷", "pronunciation": "sao", "category": "Feelings" },
    { "thai": "โกรธ", "traditional": "生氣", "pronunciation": "groht", "category": "Feelings" },
    { "thai": "กลัว", "traditional": "害怕", "pronunciation": "glua", "category": "Feelings" },
    { "thai": "เหนื่อย", "traditional": "累", "pronunciation": "nuay", "category": "Feelings" },
    { "thai": "ง่วง", "traditional": "想睡", "pronunciation": "nguang", "category": "Feelings" },
    { "thai": "ตื่นเต้น", "traditional": "興奮", "pronunciation": "teun-ten", "category": "Feelings" },
    { "thai": "สวย", "traditional": "漂亮", "pronunciation": "suay", "category": "Appearance" },
    { "thai": "หล่อ", "traditional": "帥", "pronunciation": "lor", "category": "Appearance" },
    { "thai": "ใหญ่", "traditional": "大", "pronunciation": "yai", "category": "Appearance" },
    { "thai": "เล็ก", "traditional": "小", "pronunciation": "lek", "category": "Appearance" },
    { "thai": "สูง", "traditional": "高", "pronunciation": "soong", "category": "Appearance" },
    { "thai": "เตี้ย", "traditional": "矮", "pronunciation": "dtia", "category": "Appearance" },
    { "thai": "อ้วน", "traditional": "胖", "pronunciation": "uan", "category": "Appearance" },
    { "thai": "ผอม", "traditional": "瘦", "pronunciation": "porm", "category": "Appearance" },
    { "thai": "ไก่", "traditional": "雞", "pronunciation": "gai", "category": "Food & Drink" },
    { "thai": "หมู", "traditional": "豬", "pronunciation": "moo", "category": "Food & Drink" },
    { "thai": "เนื้อ", "traditional": "牛肉", "pronunciation": "neua", "category": "Food & Drink" },
    { "thai": "ปลา", "traditional": "魚", "pronunciation": "plaa", "category": "Food & Drink" },
    { "thai": "ไข่", "traditional": "蛋", "pronunciation": "kai", "category": "Food & Drink" },
    { "thai": "ผัก", "traditional": "蔬菜", "pronunciation": "pak", "category": "Food & Drink" },
    { "thai": "ผลไม้", "traditional": "水果", "pronunciation": "pon-la-maai", "category": "Food & Drink" },
    { "thai": "เผ็ด", "traditional": "辣", "pronunciation": "pet", "category": "Food & Drink" },
    { "thai": "หวาน", "traditional": "甜", "pronunciation": "waan", "category": "Food & Drink" },
    { "thai": "เปรี้ยว", "traditional": "酸", "pronunciation": "bprio", "category": "Food & Drink" },
    { "thai": "เค็ม", "traditional": "鹹", "pronunciation": "kem", "category": "Food & Drink" },
    { "thai": "อร่อย", "traditional": "好吃", "pronunciation": "a-roy", "category": "Food & Drink" },
    { "thai": "กาแฟ", "traditional": "咖啡", "pronunciation": "gaa-fae", "category": "Food & Drink" },
    { "thai": "ชา", "traditional": "茶", "pronunciation": "chaa", "category": "Food & Drink" },
    { "thai": "นม", "traditional": "牛奶", "pronunciation": "nom", "category": "Food & Drink" },
    { "thai": "เบียร์", "traditional": "啤酒", "pronunciation": "bia", "category": "Food & Drink" },
    { "thai": "บ้าน", "traditional": "家", "pronunciation": "baan", "category": "Places" },
    { "thai": "โรงเรียน", "traditional": "學校", "pronunciation": "rohng-rian", "category": "Places" },
    { "thai": "โรงพยาบาล", "traditional": "醫院", "pronunciation": "rohng-pa-yaa-baan", "category": "Places" },
    { "thai": "ตลาด", "traditional": "市場", "pronunciation": "dta-laat", "category": "Places" },
    { "thai": "ห้างสรรพสินค้า", "traditional": "百貨公司", "pronunciation": "haang-sap-pa-sin-kaa", "category": "Places" },
    { "thai": "สนามบิน", "traditional": "機場", "pronunciation": "sa-naam-bin", "category": "Places" },
    { "thai": "วัด", "traditional": "寺廟", "pronunciation": "wat", "category": "Places" },
    { "thai": "ทะเล", "traditional": "海", "pronunciation": "ta-lay", "category": "Places" },
    { "thai": "ภูเขา", "traditional": "山", "pronunciation": "poo-kao", "category": "Places" },
    { "thai": "พ่อ", "traditional": "爸爸", "pronunciation": "por", "category": "Family" },
    { "thai": "แม่", "traditional": "媽媽", "pronunciation": "mae", "category": "Family" },
    { "thai": "พี่ชาย", "traditional": "哥哥", "pronunciation": "pee-chaai", "category": "Family" },
    { "thai": "พี่สาว", "traditional": "姐姐", "pronunciation": "pee-saao", "category": "Family" },
    { "thai": "น้องชาย", "traditional": "弟弟", "pronunciation": "norng-chaai", "category": "Family" },
    { "thai": "น้องสาว", "traditional": "妹妹", "pronunciation": "norng-saao", "category": "Family" },
    { "thai": "เพื่อน", "traditional": "朋友", "pronunciation": "peuan", "category": "Family" },
    { "thai": "วันนี้", "traditional": "今天", "pronunciation": "wan-nee", "category": "Time" },
    { "thai": "พรุ่งนี้", "traditional": "明天", "pronunciation": "proong-nee", "category": "Time" },
    { "thai": "เมื่อวานนี้", "traditional": "昨天", "pronunciation": "mua-waan-nee", "category": "Time" },
    { "thai": "ตอนนี้", "traditional": "現在", "pronunciation": "dtorn-nee", "category": "Time" },
    { "thai": "เวลา", "traditional": "時間", "pronunciation": "way-laa", "category": "Time" }
];
